logLevel = "DEBUG"
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
    address = ":80"

[docker]
  endpoint = "unix://var/run/docker.sock"
  domain = "shipstone.local"
  watch = true

[web]
  address = ":8080"
